# Generated by Django 4.1.3 on 2024-07-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_appointment_name_appointment_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.AddField(
            model_name='appointment',
            name='type',
            field=models.CharField(choices=[('physician', 'Physician'), ('neurologist', 'Neurologist'), ('psychiatrist', 'Psychiatrist'), ('oncologist', 'Oncologist'), ('dentist', 'Dentist'), ('pediatrician', 'Pediatrician'), ('gynecologist', 'Gynecologist')], default='', max_length=255),
            preserve_default=False,
        ),
    ]
