# Generated by Django 4.1.3 on 2024-07-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_appointment_user_appointment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
